### ISSUE TITLE
Better alternative to wiping MySQL database before each cycle

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#10]
Currently wipe MySQL manually before each cycle - automate this and how best? Probably could extend this to a longer period with current setup without seeing a significant reduction in how the WebApp performs and responds to user interactions

**Comment by ElliotAOram** [comment]
Closing this as I don't think we should ever have a system for automatically wiping a database. This is because if something goes wrong, the risk is too high. Since this issue was written an improved script has been produced for wiping the database which should suffice.
