### ISSUE TITLE
JavaScript exception on instrument not found page

### ISSUE THREAD

**Issue by rickybassom** [ISISScientificComputing/autoreduce#1020]
Issue raised by: developer

### What?
JavaScript exception on instrument summary page when instrument is not found.
```js
instrument_summary.js:17
Uncaught TypeError: Cannot set property 'onchange' of null
    at init (instrument_summary.js:17)
    at instrument_summary.js:28
    at instrument_summary.js:29
```
Errors like this should be caught so that other JS code can execute on the page.

### Where?
On webapp go to `/instrument/randomstring/`
Template: `/WebApp/autoreduce_webapp/templates/instrument_summary.html`

### Reproducible?
Yes

### How to test the issue is resolved
* Load the webapp and go to `/instrument/randomstring/`, the exception should not appear in the console.

**Comment by dtasev** [comment]
Seems confusing to me that changing "Filter by" automatically submits, but for the other 1/2 fields (sort by/items) you need to click apply.

I think we should just choose one, but I'm not sure whether it's best to always automatically apply or to never do it and wait for the "Apply" click. Depending on the approach we either fix this by adding a `if(select)` check or deleting that JS code
