### ISSUE TITLE
Randomly failing queue client tests in pytest action

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#1046]
Issue raised by: [developer/user/project requirement]

### What?
QueueClient tests are failing seemingly randomly withtin the pytest action.
This can be seen in more detail if you check the builds for PR #1044

### Where?
utils/clients/tests/test_queue_client.py

### How?
How did the issue come about

### Reproducible?
As this is seemingly random I cannot say what is the way to reproduce this

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by dtasev** [comment]
This should have been fixed by #1022
