### ISSUE TITLE
Remove VALID_INSTRUMENTS and instead use the DB as source of truth

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#1047]
Issue raised by: [developer/user/project requirement]

### What?
Having `VALID_INSTRUMENTS` just adds another place that we have to manually update to add an instrument. This is bothersome, and it duplicates data that already exists in the DB. Worse than duplicates because they can get out of sync.

Part of the usages (the ones in the queue processor) will be removed in #1022, but still a few remain.

Making this issue as a child of #1036 and to refer it from a commit as the reason for the removal of the `VALID_INSTRUMENTS` usage in the queue processor

**Comment by keiranjprice101** [comment]
Part of this is done in #1044

**Comment by dtasev** [comment]
Was this done in #1213 ?

**Comment by keiranjprice101** [comment]
Closed in #1213
