### ISSUE TITLE
Remove test_db_generation and populate_reduction_viewer.sql - use text fixtures instead

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#1066]
Issue raised by: [developer/user/project requirement]

### What?
test_db_generation is a test to see whether `populate_reduction_viewer.sql` was executed properly. It is a bad way of doing a global database fixture that _some_ of the tests depend on.

Remove this global fixture and adjusts the tests that use it to themselves seed the database with the required data.

**Comment by keiranjprice101** [comment]
Possibly related #758
