### ISSUE TITLE
Increase coverage fail threshold

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#1069]
Issue raised by: [developer]

### What?
Coverage threshold is too strict. For example https://coveralls.io/builds/36825252 fails on a decrease of 0.001% which is far too strict.

### Where?
Possibly `.coveragerc` or the coveralls project for the site.

**Comment by rickybassom** [comment]
I think "Coverage Decrease Threshold for Failure" can be set at https://coveralls.io/github/ISISScientificComputing/autoreduce > settings by someone who has admin privileges for autoreduction coveralls.

**Comment by dtasev** [comment]
Done, it's now 0.01
