### ISSUE TITLE
Drop Ipython back down

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#1071]
Issue raised by: [developer]
### What?
Good spot by @RebeccaBecky 
Due to the discrepancy in the python versions from the actions/build environments Ipython needs to have its dependency dropped back to the version referenced in. 3544941c72e5057c568497595579f8ecedc487c7

### Where?
Where is the issue likely to be (be as specific as possible)

### How?
Quite likely this is my mistake in approving a dependabot PR. We should also tell dependabot to ignore this dependency on its next attempt to update it.

**Comment by dtasev** [comment]
Yeah I've seen this as well. There doesn't seem to be a consistent IPython version across OS'es for whatever reason.
