### ISSUE TITLE
Remove admin "under maintenance until ... " message

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#108]
Production currently still have the "Under maintenance until ..." message for none admin users when you open it. We should remove this as it is confusing and suggests that we are not running correctly.

**Comment by ElliotAOram** [comment]
@jsws I've assigned you as I don't have admin privileges on the production WebApp. I assume I can give myself these fairly easily by adding me to the database of admins?

**Comment by jsws** [comment]
Marked notification as not active. Have also given you admin but yeah you can do it via the database

**Comment by ElliotAOram** [comment]
@jsws thanks 👍
