### ISSUE TITLE
Fallback mechanism for end-of-run-monitor

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#11]
For end of run monitor script. Should we have a fallback to monitor ICAT also for new jobs. Create an issue for this

**Comment by ElliotAOram** [comment]
We discussed that we should have a fallback mechanism (possibly 2). The current mechanism queries if the `endofrunmonitor.txt` file in each instrument directory on the data archive has changed. 
Fallback possibilities discussed include:
* Querying ICAT to check the most recent run and comparing this to the autoreduction database (MySQL db) - discussed this should be roughly once every minute or so. 
  * *If the current checking of the `.txt` files fails, ensure that when we use ICAT data, we say this in the logs.*
* Checking for actually file creation in the data archive itself and comparing this to the reduction table.

**Comment by ElliotAOram** [comment]
Remaining work:
* [ ] merge db + travis ticket
* [ ] populate local host db
* [ ] access localhost db from test 
* [ ] run as a service from daemon
* [ ] work out how best to kick off a rebuild if db is out of sync with archive
* [ ] ensure that this does not throw exceptions (should instead log output to file on error / debug)

**Comment by ElliotAOram** [comment]
restart EndOfRunMonitor when archive monitor is un-synced

**Comment by ElliotAOram** [comment]
being replaced by #203 #204 #205
