### ISSUE TITLE
Reflectometry: running the reduction outside of the Autoreduce system

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#1164]
Issue raised by: [developer/user/project requirement]

### What?
Understand how we can use and integrate the Mantid Reflectometry workflow algorithms into Autoreduction.

**Comment by dtasev** [comment]
How would you say you are doing on this @RebeccaBecky? I think you had success running it outside, and even did the next bit of running it inside the AR system. If so, can we close this issue ?

**Comment by RebeccaBecky** [comment]
Yes, we can close this issue. Thanks.
