### ISSUE TITLE
bootstrap-switch creates empty input labels on the instrument variables page

### ISSUE THREAD

**Issue by rickybassom** [ISISScientificComputing/autoreduce#1220]
Issue raised by: developer

### What?
`bootstrap-switch` creates empty input labels on the instrument variables page. This is an accessibility issue. https://www.w3.org/WAI/tutorials/forms/labels/

### Where?
The instrument variables page.

### How to test the issue is resolved
* Run the [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/) on the page and check if the warning still appears.

**Comment by dtasev** [comment]
I thought I removed all of the usages for `bootstrap-switch` in #1174.. I think the other pages include it but never render any switches intentionally
