### ISSUE TITLE
Add automatic (Selenium) testing for the WebApp

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#14]
Issue raised by: [developer]

### What?
The Web app is untested at the moment. In order to improve our stability and robustness, we should look to add unit test coverage for this. Additional consideration to adding system / performance tests (using selenium). Given the magintude of the web application this should probably separated into small issues.

### Where?
`WebApp/`

### How to test the issue is resolved
Ensure that the new unit tests work and are run (and pass) on travis

**Comment by Anders-Markvardsen** [comment]
dublicate of #487

**Comment by keiranjprice101** [comment]
@Anders-Markvardsen #487 Refers to django test frameworks and not selenium.

**Comment by Anders-Markvardsen** [comment]
> 
> 
> @Anders-Markvardsen #487 Refers to django test frameworks and not selenium.

Thanks for spotting and reopening this issue and ups apologies for not reading #487 properly
