### ISSUE TITLE
AutoreductionProcessor script ignores SIGTERM

### ISSUE THREAD

**Issue by gc-code** [ISISScientificComputing/autoreduce#141]
When the autoreduction processor is started using:
```
python autoreduction_processor_daemon.py start
```
and an attempt is made to stop it using:
```
python autoreduction_processor_daemon.py stop
```
The script hangs while repeatedly attempting to kill the process using SIGTERM. This is likely to be because the process is ignoring the signal.

**Comment by ElliotAOram** [comment]
This is not reproducible
