### ISSUE TITLE
Pylint: scripts

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#153]
Fix all the pylint errors in the following files and then update the score in travis to reflect this change:
```
./scripts/NagiosChecks/__init__.py
./scripts/ActiveMQTests/reduce.py
./scripts/ActiveMQTests/reduce_vars.py
./scripts/ActiveMQTests/__init__.py
./scripts/Build/tests/test_db_generation.py
./scripts/Build/tests/validate_icat.py
./scripts/Build/generate_apache_wsgi.py
```

**Comment by ElliotAOram** [comment]
Note: can not change name of `NagiosChecks` as I don't have access to the service to update where it looks for these. @gc-code did @jsws tell you how to access these?

**Comment by gc-code** [comment]
Yes, I have access to the Nagios service. I will look into changing the name for you.

**Comment by ElliotAOram** [comment]
@gc-code great! When you change it can we change the expected path to be `scripts/nagios_checks` probably worth you doing this in a separate pull request
