### ISSUE TITLE
Smoke testing: Queues

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#169]
Perform the following steps from the smoke testing [wiki page](https://github.com/ISISScientificComputing/autoreduce/wiki/Smoke-testing) on the Linux utilities machines (**development first and then production once we are happy with development**):

development:

* [x] Checkout
* [x] Unit tests
* [x] Queues

production:

* [x] Checkout
* [x] Unit tests
* [x] Queues

-------

Please comment on this issue any problems you encounter whilst running these tests. Don't forget to try valid and invalid behaviour.

**Comment by ElliotAOram** [comment]
Opening for cycle 18_3 smoke testing

**Comment by Anders-Markvardsen** [comment]
@ElliotAOram on https://github.com/ISISScientificComputing/autoreduce/wiki/Smoke-Testing:-Queues should there be a step on which git branch to test against and order this should be done?

**Comment by ElliotAOram** [comment]
@Anders-Markvardsen is this the information you are looking for https://github.com/ISISScientificComputing/autoreduce/wiki/Smoke-testing ?
