### ISSUE TITLE
Unable to process calibration experiments

### ISSUE THREAD

**Issue by gc-code** [ISISScientificComputing/autoreduce#180]
Calibration experiments use a string RB number rather than an integer. This means that they can't be inserted into the MySQL database because the RB number column only accepts integers.

It would be good to convert this column to a string. This would be in keeping with the way they are handled in ICAT.

**Comment by ElliotAOram** [comment]
@gc-code we should have a discussion about this next time everyone can make it to a meeting. 

The main problem here is the trade off between logical naming and actual ISIS functionality. To me atleast having an `RB  number` field in a database means I expect an integer as my value. However, storing it in a different way would just move us further from the way ISIS + ICAT do things. I'll add it to the agenda for 2 weeks time

**Comment by ElliotAOram** [comment]
Skipping calib runs
