### ISSUE TITLE
Cannot delete entities through the Django admin console

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#2]
Issue raised by: [developer]

### What?
It is currently not possible to delete a run in the admin django admin console. Attempting this on the production yields a 500 error, the development environment gives better detail on this.

### Where?
The Models code in the web application:
* [`reduction variables`](https://github.com/ISISScientificComputing/autoreduce/blob/master/WebApp/autoreduce_webapp/reduction_variables/models.py)
* [`reduction viewer`](https://github.com/ISISScientificComputing/autoreduce/blob/master/WebApp/autoreduce_webapp/reduction_viewer/models.py)

### Reproducible?
Yes

### How to test the issue is resolved
* Visit the webapp as an admin
* Go to the admin tab on the top right
* Click `Reduction Runs` in the REDUCTION_VIEWER` table
* Select a run (or multiple runs) that you wish to delete
* Choose `Delete selected reduction runs` from the drop down menu 
* Click `Go` and the run should delete without error

**Comment by ElliotAOram** [comment]
Will be potentially invalidated by Database rewrite
