### ISSUE TITLE
Improve CEPH directory for runs

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#235]
Raised by Ron Smith

Currently reduced data is saved to a CEPH directory with the following structure:

`rb\<instrument_name>\RBNumber\RB<rb_number>\autoreduced\<run_number>\<cycle_number>\autoreduce`

This contains duplicate and poorly formatted data. We would be better to use a similar structure to the data archive which is more logical and removes some unrequired directories:

`<instrument_name>\<cycle_number>\RB<rb_number>\<run_number>\autoreduce`

**Comment by gc-code** [comment]
We may be able to change anything under the 'autoreduced' directory but the DAaaS system will be dependent on the structure above that point.

**Comment by ElliotAOram** [comment]
This is not possible due to dependency on DAaaS system as stated by George
