### ISSUE TITLE
Build a better manual testing environment

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#252]
Currently it requires a lot of effort to manually test the system. Specifically, when attempting to test the end of run monitor or the flow of the system. We could improve this with the following:
* Create an environment that will allow a full end to end test of autoreduction. This must do:
  * Create fake archive
  * Create fake ceph directory
  * Ensure autoreduction setting points to both
  * Have a function to add a batch of files into the end of run monitor
It should be possible to use much of the existing code but this needs to be combined to make it easy to use

**Comment by dtasev** [comment]
Made better with #779 and #1022. Fake archive and CEPH exist to a degree but we're reviewing their usefulness in #875
