### ISSUE TITLE
Remove data redundancy in the database

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#285]
Issue raised by: [developer]

### What?
The database table `reduction_varaiables_variable` has a massive amount of duplicated data. It appears that the variables used to run a particular reduction job are stored even if they are the same as the variables used before. Given that we already have a linking table (`reduction_variables_runvariable`) this is needless duplication and is not only filling up our database, but also bad design. Instead of mindlessly adding new variables we should instead check if for pre-existing variables that are identical to the current variables.

### Where?
Will have to investigate where, as well as ensure there is not a good reason why, this information is duplicated - not reused. 

### How?
Discovered while writing a script to remove records manually and failing the foriegn key constraint in `reduction_variables_runvariable`. Subsequently looking at the database and discovering the duplication. 

### Reproducible?
This is currently the state live on production

### How to test the issue is resolved
Ensure that when a job is submitted with the same parameters as a different job, the information is not duplicated in the database:
1. Submit a run using manual submission
2. Check the variables have been added to the reduction_variables_variable table in the database
3. Submit the same run
4. Check that the variables have `NOT` been added to the database but instead the `reduction_variables_runvariable` table links the reduction_id to the variables from the previous run

Note: This should be in place before next cycle starts (It will be too difficult to attempt to rectify this in the current database)

**Comment by ElliotAOram** [comment]
Note: at the time of making this issue, the production server record numbers are the following:

| Table                                  | Total records | Unique | possible reduction |
| -------------------------------------- | ------------- | ------ | ------------------ |
| reduction_variables_variable           | 137153        | 44     | 3117 times smaller |
| reduction_variables_runvariable        | 78621         | 78621  | 0                  |
| reduction_variables_instrumentvariable | 58230         | 12     | 4857 times smaller |

**Comment by dtasev** [comment]
We're going to have to look at this one again, and probably ASAP
