### ISSUE TITLE
Investigate if Autoreduction should listen and display announcements from other services

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#287]
Issue raised by: Anders

### What?
Have the webapp to optionally listen (or scan) announcement channels. For example for news about the target stations and beamline - has there been a catastrophic feature and so on. At ISIS we have the MCR channel, which is e.g. displayed on https://www.isis.stfc.ac.uk/Pages/Beam-Status.aspx. The webapp don't want to display all MCR messages, but perhaps a those messages that inform the target station is down, maintenance day, not in cycle etc.

This is set as low priority and needs investigation. Firstly it should not be considered for development before it has been discussed with customers

### Where?
Webapp

### How to test the issue is resolved
To be decided when speaking to customers. One output from speaking to customers would be to close this issue

**Comment by ElliotAOram** [comment]
Out of scope of this project for now
