### ISSUE TITLE
Calibration runs throw exceptions

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#29]
If a run is submitted and that run has an RB number that is not an integer (for example CAL_GEM_21/10/2017) then the queue processor throws an exception when trying to insert that run into the database, because the database requires an integer.

We should decide how we want to deal with calibration runs.

**Comment by ElliotAOram** [comment]
Do we actually want to be reducing calibration files?

**Comment by ElliotAOram** [comment]
Additionally you can't re-run these because of the folder format issue

**Comment by ElliotAOram** [comment]
@jsws by reference number do you mean RB number? or is this something else? We should discuss this in Wednesday's meeting.

**Comment by jsws** [comment]
@ElliotAOram Yeah I meant RB number

**Comment by ElliotAOram** [comment]
Fixed by skipping calib runs
