### ISSUE TITLE
Allow users to overwrite queued runs 

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#302]
Issue raised by: [user: ENGINX]

### What?
Runs that get stuck in the queued state are never removed and this can result in holding up other runs / stopping users from re-running runs that are stuck in queued state. We should allow users to overwrite runs that are in the queued state. However we should produce a warning message when doing this to ensure that users understand that they are overwriting a run.

### Where?
* Web app run summary page requires additional check (message box for overwriting queued runs)
* Ensure that the webapp actually is able to remove queued runs (we currently do not allow this by default.
* Ensure the database is updated to skip the run that is stuck in queued state. The run should not be removed as this would not be an accurate representation of the real-world state of the system. instead we should either change it to the `Skipped` status or add a new status `Cancelled`.

### Reproducible?
[Yes]

### How to test the issue is resolved
* Add a run to the Queued state:
  * Probably easiest to do this via submitting a run to the database, allowing it to complete and then manually updating the status in the database to "Queued" in the reduction_viewer_reductionrun table.
* Attempt to overwrite this run using the webapp you should see the following:
  * Normal re-run interface
  * When you click submit it should bring up a warning that you are overwritting the queued run.
  * Ensure this can be done from anywhere it is possible to re-run a reduction job

**Comment by dtasev** [comment]
Should not be able to get stuck in queued with #1022
