### ISSUE TITLE
Test cloud compute nodes (static servers)

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#327]
Issue raised by: [developer]

### What?
After completion of #326 we should expand to try and use multiple nodes for compute resource on the cloud. This will require 2 nodes to be subscribed to the same ActiveMQ instance (to my knowledge this should be fine)

### Where?
Cloud nodes

### How to test the issue is resolved
1. Ensure that the development queue processor is not running
1. Start 2 cloud instances and use the ansible script to set them up as compute nodes
1. Ensure both compute nodes are pointed to the development ActiveMQ instance
1. Batch submit 10+ runs using the manual submission script
1. Ensure that all runs are reduced
1. Inspect the log files on each of the machines and ensure that they both ran some of the submitted runs. 
1. Ensure no runs were missed / duplicated
1. Allow the End of Run Monitor to submit some runs and ensure that these are processed.

**Comment by dtasev** [comment]
This can now be done easily after #1022
