### ISSUE TITLE
New EoRM: Sometimes uses incorrect RB number

### ISSUE THREAD

**Issue by gc-code** [ISISScientificComputing/autoreduce#329]
Issue raised by: developer

### What?
EoRM sometimes reads the wrong RB number on instruments where run numbers are truncated. I think the best approach to solving this will be just to use the last RB number like the current EoRM.

### Where?
New EoRM

### How?
When testing on the development environment I observed that some RB numbers are being reported incorrectly.

### Reproducible?
Yes

### How to test the issue is resolved
RB numbers are reported correctly.

**Comment by ElliotAOram** [comment]
Maintenance day branch candidate
