### ISSUE TITLE
Setup and Configuration of Sentry

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#342]
Issue raised by: [developer]

### What?

The setup and configuration of Sentry data aggregation tool on a cloud instance for self hosting to pilot throughout next cycle.

Sentry has the potential to offer gainful insights about bugs found in or directly affecting Autoreduction, decreasing the amount of time dedicated to debugging and resolving issues. 

### How to test the issue is resolved

Attach web-hook to existing error logs generated.
Compare output of errors from log file and Sentry
Test integrations with email client, Github and Slack
Remove need to send QueueProcessor errors to log file.

**Comment by ElliotAOram** [comment]
Sentry is now running on production so I thinking this setup/config issue can be closed
