### ISSUE TITLE
Investigate how to observe state of ActiveMQ

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#343]
Issue raised by: [developer]

Refer to Jack for known Solutions

### What?
In order to monitor the current state of activeMQ, we need a way to programatically check the messages it has without destroying any of them. The ideal scenario would be the ability to list all the messages in each individual queue in a non-destructive way. 

### Where?
The will be in the QueueProcessor / ActiveMQ access credentials but it is mostly spike work. 

### How?
This is a sub issue of #302 

### How to test the issue is resolved
Either:
* Post your findings in the parent issue for use in resolving that issue

OR 
* Create a small script (perhaps this can go into the `scripts` directory) for listing all the activemq messages (this is not required if it's a simple API call).

**Comment by dtasev** [comment]
It would be very nice to be able to do this

**Comment by JackEAllen** [comment]
@dtasev If I remember correctly, this may not be possible. 
Provided I am remembering correctly, the only way to do this is to consume messages and then try to re-create them in place which could prove to be very difficult and error-prone. 
In the end, the decision was made to prioritise moving to Kafka instead which allows for such capabilities as viewing message state non-destructively.
If Kafka is still a priority within the project development roadmap, may be worth closing this issue.

**Comment by dtasev** [comment]
> Provided I am remembering correctly, the only way to do this is to consume messages and then try to re-create them in place which could prove to be very difficult and error-prone.

We can't do this at all anymore, and as you said, it just sounds like a bad idea.

> In the end, the decision was made to prioritise moving to Kafka instead which allows for such capabilities as viewing message state non-destructively. If Kafka is still a priority within the project development roadmap, may be worth closing this issue.

Sounds like Kafka is indeed the way to go. It's still on the roadmap and I'd estimate a good point would be the coming long shutdown.

Thanks for the update Jack!
