### ISSUE TITLE
Use Mantid docker for reduction

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#347]
Issue raised by: [developer]

### What?
The QueueProcessor needs to be hooked up to use the Mantid docker container rather than relying on Mantid being present on the system. 

### Where?
This will be in `QueueProcessors/AutoreductionProcessor/post_process_admin.py` file and require knowledge of how to use `docker_reduction/mantid`. 

### How to test the issue is resolved
Ensure that files can be successfully reduced on a compute node without mantid being installed. You can set up this compute node using the ansible-compute scripts in the build repository

**Comment by ElliotAOram** [comment]
This also needs to ensure that the logs from mantid are recoverable (might be a separate PR)

**Comment by dtasev** [comment]
For this we'd need another refactor/rewrite of the ReductionRunner so this isn't happening until we need more than Mantid for reductions.
