### ISSUE TITLE
produce a better way of monitoring status on webapp

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#35]
We should look into a better way to monitor the state of runs in the webapp. The current interface might say something like: `WISH (18) Error` but this tell us nothing about the error at a glance, the most important parts being  the time the error occurred and more importantly has a rerun been attempted and was it successful. I feel this is going to be useful for us as developers as well as users.

The most obvious solution for this for this is an interactive graph. For a given instrument, plot the run status   against time. Highlighting a node on the graph can then tell you the run number, etc.

![image](https://user-images.githubusercontent.com/13132128/39045897-336e3c76-448c-11e8-93fc-22fcbbb53863.png)

There a variety of chart creating frameworks written in javascript that we can do this with - we should research the most choice before starting work on this however

**Comment by DominicOram** [comment]
We're currently looking into using Grafana (https://grafana.com/) for some graphing on our web dashboard. It was quite easy to set up.
