### ISSUE TITLE
Standardise Logging Format

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#353]
Issue raised by: [developer]

### What?
Currently, we log a lot of information into log files using a specific format, but don't follow the same format for logging errors despite being sent to the same log file.

Ideally, it would be nice to have a standardised format for all logs. This will allow for better error tracking in sentry as there will be more context associated with errors logged.

### Where?
All files that write to log files in the following location:
autoreduction/logs/

### How?
Either follow the suggested format below or similar for logging files:

```
	log_id						INT 		AUTO_INCREMENT,
	run_number					INT,
	rb_number					INT,
	instrument					VARCHAR,
	data						        VARCHAR,
	error_code					INT,
	error_description			        TEXT,
	date_logged					CHAR(10),
	time_logged					CHAR(8)
);
```

### How to test the issue is resolved
All log files will store the same format for every level of message logged

**Comment by keiranjprice101** [comment]
No longer an issue as root logger set correctly in #796, #798
