### ISSUE TITLE
Design and Develop a Data Domain and Data Persistence Layer

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#364]
Issue raised by: [developer]

### What?
Create data domain and persistent layers to store and execute SQL queries to make Autoreduction more modular overall. 

- Note we don't want full persistence which is why we want to create and destroy the connection as and when needed. 

Below is a link to a basic design to be used as a template:
https://drive.google.com/file/d/1NM1j2W2VsUbEIAF-domck8RZR-vvSZCb/view?usp=sharing

### Where?
All SQL queries throughout application should be moved. 

### How?
Create two separate classes for isisICAT and local Autoreduction database to construct SQL queries based on input variables from files that wish to run queries. 

Send the built query through persistence layer to create connection, execute query and then destroy the connection again. 

### How to test the issue is resolved
* Test SQL Queries on:
- local Autoreduction on development database
- Mock of isisICAT

*Test creation and teardown of database connections

**Comment by ElliotAOram** [comment]
On Hold pending finalisation of database refactoring

**Comment by ElliotAOram** [comment]
Replaced by database to DjangoORM which has it's on inbuilt persistence
