### ISSUE TITLE
Refactor Hot Fixes from Python 3 Compatibility Upgrade

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#376]
Issue raised by: [developer]

### What?
Many changes were made to the Autoreduction codebase to fix any incompatibilities when upgrading to Python 3 before end of life. 

We should go back to create more permanent fixes for these changes where applicable to maintain a clean and readable codebase.

### Where?
1.  All of Autoreduction codebase
2. QueueProcessors/AutoreductionProcessor/daemon.py

### How?
1. Change all usages of %s for string formatting to {} notation. 
2. Put inside `with` and remove `pid_file.close()` on lines 113-116 inside QueueProcessors/AutoreductionProcessor/daemon.py if possible.

### How to test the issue is resolved
1. Check returned strings are formatted correctly
2. Check `pid_file` is  read and closed correctly.

**Comment by ElliotAOram** [comment]
Closing as this to changes in a branch that is too stale. May reopen if similar adjustments are made
