### ISSUE TITLE
Plotly Dash Application to be Served as Part of Autoreductions Django Application

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#377]
Issue raised by: [developer]

### What?
Currently to have Plotly visualisations visible inside the Autoreduction WebApp, a separate web service is required to be ran alongside the Django application. This was a constraint caused by using Python2. 

Now that Autoreduction is using Python3, we can take advantage of a package called [django-plotly-dash](https://django-plotly-dash.readthedocs.io/en/stable/introduction.html) to serve Plotly up as part of Autoreductions Django application.

### Where?
- WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
- WebApp/autoreduce_webapp/autoreduce_webapp/urls.py

### How?
*Installation and Initial Configuration*
1. install django_plotly_dash
2. Add `django_plotly_dash.apps.DjangoPlotlyDashConfig` to Installed Apps inside settings.py
3. `django_plotly_dash.middleware.BaseMiddleware` will need to be added to MIDDLEWARE in the same file.
4. Applications roots will need to be registered in urls.py. `path(‘django_plotly_dash/‘, include(‘django_plotly_dash.urls’)),`
5. A migration will be needed after following the above steps to update the database. 
6. Perform tests detailed below

*Tests for Configuring Live State*
1. Install channels daphne redis django-redis channels-redis if not already installed
2. Run the following commands to run redis with use of a docker container: 
```
docker pull redis:4
docker run -p 6379:6379 -d redis
```
Alternatively, the prepare_redis script will run both of these commands.
3. Create a CHANNEL_LAYERS entry in settings.py following a similar structure as shown below: 
```
INSTALLED_APPS = [
    ...
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels', # Make sure to add channels to INSTALLED_APPs here
    ...
    ]
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379),], # Should be changed to match network location of redis instance
        },
    },
}
```
4. Run a migration to update database. 
5. Repeat tests again

### How to test the issue is resolved
1. Check WebApplication still works as expected.
2. Check `plotly_app` tag in the `plotly_dash` tag liblrary can thenb be used to render a [registered dash component](https://django-plotly-dash.readthedocs.io/en/stable/simple_use.html#simple-use) - I recommend creating a new blank page temporarily to test this for simplicity

**Comment by ElliotAOram** [comment]
@JackEAllen what is the status of this?

**Comment by ElliotAOram** [comment]
@JackEAllen is this still relevant?
