### ISSUE TITLE
SQL Monitor Scripts

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#378]
Issue raised by: [developer]

### What?

It would be nice to have a few scripts to run SQL queries to monitor the state of Autoreduction.

This should include queries to look at:
- Failures in the last 24 hours (including the weekend in Monday) 
- Missing run numbers e.g if (1, 2, 3, 5, 6) in DB, will report that 4 is missing. 

Other potential areas to monitor include:
* Average execution time (per instrument or as sum of instruments) - per day, per week per month and per cycle
* Frequency of runs for each instrument and overall - per day, per week, per month, per cycle
* Number of re-runs and how re-run was initialised (Internal, External or Automated)
Number of failures per cycle. And of those re-runs how many were successful / failures.

### Where?
autoreduce/scripts/

### How?
Having a few scripts to monitor the state of Autoreduction will allow for better real time monitoring and for historical analysis. 

### How to test the issue is resolved
- Check connection to Database is present
- Test that Expected Data is returned when each query is executed

**Comment by ElliotAOram** [comment]
As an extension to this task (in a separate issue) we may also want to be able to produce a report that details all the above queries for a single cycle in an easy to visualise manner. We can define this better later on

**Comment by dtasev** [comment]
This should be done with ORM not SQL, and probably be part of the Nagios checks
