### ISSUE TITLE
New Github Repository to Store Reduction Scripts for Archiving Using a Cron Job

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#379]
Issue raised by: [developer]

### What?
Design a cron job to push corresponding reductions scripts for each instrument using Autoreduction into an ordered format in a new GitHub repository for archiving purposes. 

### Where?
A new appropriately named GitHub repository containing directories for each Instrument

### How to test the issue is resolved
- Test if the cron job can create a new directory for a reduction script for a new instrument if not already present on repository.
- Test that the cron job can push a new reduction script to GitHub for a given time period (every 5 minutes) only if a change has been made to the reduction script. 
- Test if the Cron Job can handle Merge Conflicts

**Comment by ElliotAOram** [comment]
New repository for script storage https://github.com/ISISSoftwareServices/AutoreductionScripts
