### ISSUE TITLE
Associated run versions in webapp 

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#381]
Issue raised by: [developer]

### What?
Currently if a run is resubmitted a new version is added to the database with a different version (increment `run_version` field in `reductionrun` table). These new versions then get displayed in the overview page for the instrument e.g. `MAR1234 - 1`, `MAR1234 - 2`, etc.

To make things more obvious for the user, I would suggest a new default filtering option (in the overview page) where ONLY runs are displayed (not run versions) and when that item is clicked all the associated runs, and their status, are displayed. We should then have the other option to filter by reduction job which shows all runs and there versions as we do currently. 

### Where?
This will be a change in the webapp. Specifically this will affect the `instrument_summary` and `run_summary` functions (`Webapp/autoreduce_webapp/reduction_viewer/views.py`) AND he corresponding `.html` pages (see function `@render_with` tags for html pages)

### How to test the issue is resolved
* Locate a run that has multiple versions associated with it
* Login to the webapp
* Find this run in the webapp and ensure that it does NOT show multiple versions
  * Click this run and then see that there are multiple versions associated with it.
* Go back to the main page and click a run with no associated versions
  * Ensure that there are no associated versions with this run
* Go back to the main page and change the filtering option to `reduction job`.
  * See that this show all runs and versions of run

**Comment by ElliotAOram** [comment]
This is low priority as it has not been asked for by users

**Comment by dtasev** [comment]
Closing as not requested
