### ISSUE TITLE
Ensure variables are ordered correctly in the webapp

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#390]
Issue raised by: [user]

### What?
Currently the variables that are added to the webapp are added in a random order. To avoid user confusion we should order these. The order in the web app should reflect that of the reduce_vars.py

### Where?
I believe the cause of the issue takes place here: 
`_update_variables` inside `WebApp/autoreduce_webapp/reduction_variables/utils.py` 

It's likely that the database is overwriting the order of the dictionary. 

### How?
User requirement

### How to test the issue is resolved
* Find any run summary page (click a run from the list of reduction jobs on the instrument summary page)
* Ensure that the variables in the re-submit section are in the same order as those defined in the corresponding reduce_vars.py file (`\\isis\inst$\NDX<>\user\scripts\autoreduction\reduce_vars.py`)

**Comment by JackEAllen** [comment]
When running the webapp in debug mode it's clear that the dictionary is now holding the correct order used in the reduce_vars.py. However, this always gets overwritten by the order inside the database which does not follow the same order as reduce_vars.py

**Comment by ElliotAOram** [comment]
I have just wiped the dev environment for other reasons. Can you see if the new runs producing variables in the correct order?
