### ISSUE TITLE
Review of user facing documentation

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#416]
Issue raised by: [developer]

### What?
The user documentation is not the best and could be improved we need to discuss the way in which we would like to present users with the help documentation.

@ElliotAOram is in favour of bitesize videos to make information obvious and easy to digest. Obviously this is a larger maintenance overhead but would be highly beneficial. 
alternatively an interactive tour of the webapp through notification

### Where?
New design / proposal document to cover changes to user documentation

### How to test the issue is resolved
* Ensure that the changes are logical and feasible

**Comment by JEThompson97** [comment]
@ElliotAOram 
This issue might be ready to close now?

**Comment by ElliotAOram** [comment]
Agreed
