### ISSUE TITLE
Date in Cycle Handler

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#437]
Issue raised by: developer

### What?
A means to compare a given date with cycle dates to determine which cycle dates to use within sql queries by controller.

### Where?
scripts/system_performance/

### How?
Create a script to compare a given date against dates pulled from the beam status webpage to check if in cycle or not. 

### How to test the issue is resolved
* Ensure all unit tests pass.
* Ensure there is no drop in coverage.

**Comment by ElliotAOram** [comment]
Replaced with BA cycle ingest
