### ISSUE TITLE
Inactive Help Page Login URL. 

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#438]
Issue raised by: developer

### What?
When logged out/timed out, the help page login url in the navigation bar does not take the user to the login page. 
Ideally, the user should be rerouted the the login page. 

### Where?
* http://reduce.isis.cclrc.ac.uk/help/
* WebApp/autoreduce_webapp/templates/help.html
* WebApp/autoreduce_webapp/templates/navbar.html

### How?
The help page currently seems to be treated as a special case when it should ideally follow the same procedure as all other pages on the Autoreduction Webpage by being rerouted to the login page. 

### Reproducible?
Yes

To replicate this problem, a user must be timed out due to inactivity in the web-app when accessing the help url or navigate to the help url first and wait until the session expires. 

### How to test the issue is resolved
When your session has timed out in the web-app, check if you are rerouted to the login page when either:
* Trying to navigate the the help page from another page.
* Attempting to log in using the navigation bar option from the help page.

**Comment by rickybassom** [comment]
I've tested this issue under production and it appears to no longer exist. I will close this issue.
