### ISSUE TITLE
Improving logging from multiple instruments

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#44]
Issue raised by: [developer]

### What?
At the moment all of our logs from every instrument are stored in a single log file and are poorly separated.
This was fine when we only had one or two instruments, but now there are 5 it is becoming unmanageable.  My recommendation would be separate the logs into each instrument e.g. 
```
GEM_autoreductionProcessor.log
WISH_autoreductionProcessor.log
...
```

We could implement this simply by having a function that takes log level (`DEBUG`, `INFO`, etc.), instrument and message:
```
log_message(self.instrument, logging.WARNING, "something went wrong")
``` 

### Where?
* `End of Run monitor`
* `QueueProcessor`
* `Autoreduction processor`

### How to test the issue is resolved
* Run an end to end test for autoreduction using the manual submission script
` python scripts/manual_submission/manual_submission.py <INST> <RUN_NO>`
* Repeat with a different instrument
* Ensure that separate log files are produced for each instrument
* Repeat this one of the first instrument used above
* Ensure this goes to the correct log file

**Comment by dtasev** [comment]
I like this. We should do it

**Comment by dtasev** [comment]
Closing as this is not worth doing as an independent task right now. When #1186 comes to a conclusion we'll likely have a solution for both this and centralised logging.
