### ISSUE TITLE
Webapp access to experiment summary page

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#440]
Issue raised by: [developer]

### What?
It is not currently possible to click the RB numbers and see the experiment information in the webapp. This is because that currently collapses / expands the associated run numbers.

### Where?
Webapp run_list 

### How to test the issue is resolved
* Open the web app
* Select an instrument
* Change to filter by RB_number
* Apply filter
* Click on an RB number and observe that you go to the experiment summary page
* Go back 
* Click around the RB Number (on the row) and ensure it expands the list of runs

**Comment by JEThompson97** [comment]
@ElliotAOram 
Looking into this issue - as far as I can see "run_list.html" doesn't exist?
Am I missing something?
![image](https://user-images.githubusercontent.com/31534888/77426969-75c83600-6dcd-11ea-960a-389be4749012.png)
![image](https://user-images.githubusercontent.com/31534888/77427098-b031d300-6dcd-11ea-839e-920a98835933.png)
