### ISSUE TITLE
Clean Maintenance Days Data Collected by Web-scraper

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#442]
Issue raised by: developer

### What?
Currently the data scraped from the beam status web page does not clean the maintenance days column.

This column should also ideally be cleaned for use in preventing the system performance checks, querying for data when instruments are not active when called from a cron job. 

The Maintenance Days column should be converted into a list of dates in string format e.g. for cycle 2020/02, the maintenance days column would look like: ` ['2020-09-23',  '2020-10-07'] `

The first two columns in the dataframe output should look like this in turn:

|      | Cycle       |   Target        |   Start              |   End                |   Maintenance day(s)                 |
| -- | --------- | ------------ | -------------- | -------------- | ------------------------------ |
| 0  | 2020/03   |  TS1 & TS2  |   2020-11-10  |   2020-12-17   |   [2020-11-25]                           |
| 1   | 2020/02    |  TS1 & TS2  |  2020-9-08   |   2020-10-23  |   [2020-09-23,  2020-10-07]   |

To view the scripts output, you can add a print statement to the end of the script to print the DATA_FRAME variable on line 206  ( `print(DATA_FRAME)` ) to display the cleaned pandas dataframe for manual testing.

### Where?
Inside the DataClean Class.
scripts/system_performance/cycle_webscraper.py

### How?
To meet the need to integrate maintenance days into the Date_in_cycle script to prevent system state checks being ran when instruments are not active. 

### How to test the issue is resolved

* Ensure that dates cleaned in the maintenance days column match the same date format as the start and end cycle dates columns.

**Comment by ElliotAOram** [comment]
closing as replaced by new soap client impl
