### ISSUE TITLE
Input Validation Handler Script

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#443]
Issue raised by: developer

### What?
Create an input validation handler script to validate the source of the scripts access which will either be from a cron job or from another script taking user inout directly which also verifies method input arguments and calls, checks if a given date is in a cycle or not to run queries within an appropriate date range that matches the dates for a given cycle.

### Where?
scripts/system_performance

### How?
To meet the need to provide statistics about the performance of Autoreduction

### How to test the issue is resolved
Ensure all unit tests pass
Ensure there is no drop in coverage

**Comment by ElliotAOram** [comment]
No longer required with new monitoring repo
