### ISSUE TITLE
500 error displayed rather than actual error

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#45]
After investigating the logs for GEM 84414 I discovered it failed due to not being able to find the .nxs file when the mantid script was run. However rather than displaying the error from the stack trace, a 500 error is displayed: http://reduce.isis.cclrc.ac.uk/runs/84414/0/ 

In POLARIS scripts, we have seen the same failure, but this does not produce the 500 error, but instead displays the mantid stack trace: http://reduce.isis.cclrc.ac.uk/runs/108560/0/

We should be consistent in our error reporting. I think the mantid stack trace is far more useful in this case.

**Comment by ElliotAOram** [comment]
This is not present on the development node. Until it is updated to the git repository, we can have no real confidence of exactly what code is running on the production node as such this issue should be revisited if it persists when the production code is updated

**Comment by jsws** [comment]
Looking in the web app log this is happening because GEM run 84414 has an RB number of `-1000`  (often used for calibration runs) and the web app can't deal with negative RB numbers. 

web app log:
```
[30/Apr/2018 11:42:24] ERROR [django.request:135] Internal Server Error: /runs/84414/0/
...
NoReverseMatch: Reverse for 'experiment_summary' with keyword arguments '{u'reference_number': <Experiment: -1000>}' not found. 1 pattern(s) tried: ['experiment/(?P<reference_number>[0-9]+)/$']
```

This explains issue #46 too.
