### ISSUE TITLE
IMPLEMENT: Plot Handler

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#480]
Issue raised by: [project requirement]

### What?
Implement the plotHandler class- which acts as the controller for the plot functionality. This class is responsible for:
* Getting the plotting file (via the SFTP client #470)
* Getting the plot type from the autoreduction database (via the database client)
* Getting the associated plotting meta data file (#474)
* Instructing the Plotting factory to build an IFrame based on the above

This class must be accompanied by a full set of test cases. Given the `How to test` section below, it may be better to develop this with TestDrivenDevelopment. 

This implementation should match the design:

![image](https://user-images.githubusercontent.com/13132128/75336811-b3e04180-5883-11ea-9471-d2d0459f7548.png)

### Where?
This will be a new class in the plotting module

### How to test the issue is resolved
* Try running the following scripts and ensure their outputs:
```
iframe = PlotHandler('MARI', rb_number=1968049).construct plot()
> NotImplementedError "Plotting of RB numbers are not currently supported, please specify a run number"

iframe = PlotHandler('MARI', run_number=27070).construct_plot()
# Should return a string representation of a iframe that will show the data for this run
# Discuss this with whoever implements the plotting factory + plotting meta language

iframe = PlotHandler('MARI', run_number=1).construct_plot()
> RuntimeError "Unable to find run number 1 in the autoreduction database"

iframe = PlotHandler('Fake instrument', run_number=27070).construct_plot()
> RuntimeError "Unable to find instrument 'Fake Instrument` in the autoreduction database"
```

**Comment by keiranjprice101** [comment]
closed in #573
