### ISSUE TITLE
Add test framework for WebApp

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#487]
Issue raised by: [developer]

### What?

- Currently, there is no test framework for the WebApp.
- [This link](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing) describes best practice for setting this up for Django.
- Once this has been implemented, tests for the WebApp should be implemented within this framework.

_Screenshot from the link above:_
![image](https://user-images.githubusercontent.com/31534888/75789795-2492cc80-5d62-11ea-91ab-67b0cfef426c.png)

### Where?
- The entire `WebApp/` folder

### How?
We decided a test framework is needed when coverage dropped in response to added functionality from #485

**Comment by Anders-Markvardsen** [comment]
A initial plan for this done, see https://github.com/ISISScientificComputing/autoreduce-documents/blob/master/projects/selenium/design.md
