### ISSUE TITLE
Remove experiment summary where RB Number = 0

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#497]
Issue raised by: [developer/user/project requirement]

### What?
* The RB numbers within the (i) run_summary page and (ii) RB number filtered list link to the experiment summary for that RB. (see screenshots below).
* In cases where RB number = 0, **do we want to this to link to an experiment summary?**

_(i) run_summary page_
![image](https://user-images.githubusercontent.com/31534888/77425346-81662d80-6dca-11ea-916c-c3d546849ed1.png)

_(ii) RB number filtered list_
![image](https://user-images.githubusercontent.com/31534888/77426253-09006c00-6dcc-11ea-9188-3865f325028e.png)

* This seems undesirable to me because as far as I understand, runs where RB=0 do not all necessarily link to the same experiment.
  * Would you be able to confirm @ElliotAOram ?

### Where?
The Run Summary page

### How to test the issue is resolved
- Ensure there is no link when RB number = 0

**Comment by ElliotAOram** [comment]
I think it is still important to show the `RB0` experiment for completeness. What we used to do was not display any `RB0` or less runs. However, this actually caused more confusion as people were not able to see the calibration runs. 

Having said this, I agree that the experiment page could use some work as it is rather mangled. These problems are further highlighted on the `RB0` page as it contains large amounts of spread out data. 

@JEThompson97 Let's discuss this on zoom when you are next free
