### ISSUE TITLE
Add an interactive tutorial

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#508]
Issue raised by: [developer/user/project requirement]

### What?
Follows on from #416

- In pursuit of a better way of presenting help documentation to users, @ElliotAOram discussed the idea of implementing an interactive tutorial for the WebApp.
- This would allow the user to click through information boxes which highlight and explain various features of the WebApp.
___
- This issue involves:
  * An investigation into what existing packages which can fulfil this requirement.
  * Testing of any potential package(s) - including feasibility testing of whether the time/effort to apply to our WebApp is reasonable.
  * For the most promising package: Implementing a prototype of how we can apply this to the WebApp.
  * If the prototype is successful: Developing the prototype into a full implementation.

### How?
- This issue spawned out of discussions regarding how we can best teach users how to use the Autoreduction WebApp

### How to test the issue is resolved
- Assess whether the interactive tutorial implementation is ready to be deployed

**Comment by JEThompson97** [comment]
Ander's comments (27/4/2020)

> I like this user facing feature.
> I like the texts and the look and feel of it, and I have no suggestions for improvement to these specific aspects.
> However, the following software engineering questions came to me:
> • From a software maintenance engineering point of view how does this fit in? I.e. could this tour get out of sync with what the WebApp does? If yes, have you thought about the best mechanism for mitigating this?
> • Have you tested how the tour looks on a mobile as compared to a PC? Is the aim for the tour to be supported on all devices or only some?

**Comment by ElliotAOram** [comment]
Will close this and @JEThompson97 to make sub issues for other pages

**Comment by JackEAllen** [comment]
It would be nice if there was a smooth fade transition from one instruction to another.
Currently the background jumps very abruptly in and out of focus.
It would be nice if the background stayed out of focus when focusing on another section of the webpage using a transition.
If this proves to be challenging, I would suggest just adding transitions to allow the background to fade in and out of focus instead of changing so abruptly.
