### ISSUE TITLE
Experiment information is not displayed

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#51]
When viewing some experiment pages the information related to that experiment is not displayed, for example on RB1810084 the title, PI and Instrument are missing.

![image](https://user-images.githubusercontent.com/5903484/39535951-1f2c2408-4e2d-11e8-8b06-5c50661db329.png)

**Comment by ElliotAOram** [comment]
Will review this now to see if it s reproducible

**Comment by ElliotAOram** [comment]
This is still relevant hence I shall remove the `Review` label
