### ISSUE TITLE
Integrate AMQ Message into autoreduction

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#512]
Issue raised by: [developer]

### What?
We need to add the AMQ Message implementation (`message.job.Message`) from #507 into autoreduction. If this is proving large then we could try and break it up a  bit. This code is used throughout the project. Before changing any implementation code, we must check that we have tests that cover what a particular function sends to AMQ. For this issue, we should be sending the exact same information in the same format to AMQ as we were before. So in short in this issue you should:
1. Identify the areas of the code base that currently use AMQ to send / receive messages
2. Assess if this issue should be partitioned to avoid it become large (dependant on findings from (1))
3. Select an area to start in (I would suggest run_detection is probably easiest)
4. Ensure that there are tests to check what is sent to AMQ in all appropriate execution states  including the type of the data sent to AMQ (if none implement these first)
5. Change the code to use the AMQ Message class
6. Ensure the tests still pass

### Where?
* monitors/run_detection.py
* queue_processor
* autoreduction_processor
* webapp

### How?
continuation of #507 as part an initial step for the database re-design

### How to test the issue is resolved
* All test must pass
* Test must validate what is sent to AMQ
* Implementation must use AMQ Message class
* We should also validate that all is well on the development environment too

**Comment by JEThompson97** [comment]
Now that all raw instances of stomp to access AMQ have been removed, and all usages of QueueClient  to access AMQ that should be tested have tests, the next step of this issue is:
- In line with the second part of step 4. (below), double check existing tests check for the data **type** being sent
> "including the type of the data sent to AMQ"
- Integrate the Message class
> "Change the code to use the AMQ Message class"

**Comment by JEThompson97** [comment]
#### Update as of 29/05/20 (my last day in autoreduction):
Once all related open PRs are merged, the only part of the code base the Message class has not been integrated is the WebApp
