### ISSUE TITLE
Remove queue_client.serialise_data

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#549]
# HOLD PENDING #512

Issue raised by: [developer]

### What?
- Once the Message class is fully integrated `queue_client.serialise_data` should no longer be used/needed
- This is because the method is used to package data into a dict, ready to send to a processor-queue. However, as we are moving to using the Message class for sending data to the queue, this method becomes irrelevant. 
- Additionally, if data is required in dict form, the Message class contains this functionality, so it is redundant in the queue_client.

Note: Tests will also need to be refactored to accommodate this change

### Where?
`\utils\clients\queue_client.py`

### How?
As part of #512

### How to test the issue is resolved
- `queue_client.serialise_data` is removed
- All tests still pass

**Comment by keiranjprice101** [comment]
This was closed in #591
