### ISSUE TITLE
Refactor Message attributes

### ISSUE THREAD

**Issue by JEThompson97** [ISISScientificComputing/autoreduce#574]
Issue raised by: [developer]

### What?
- After the Message class is integrated (#512), the next step will be to refactor it's attributes.
- To make the integration process simpler, we retained the old dictionary keys.
- We would like to update the attribute names to be more helpful and intuitive.

#### Additional notes
- There's currently duplicate attributes: `description` and `run_description`

### Where?
`message/job.py`

### How to test the issue is resolved
- Ensure all tests still pass and behaviour is as expected when run on the dev node

**Comment by keiranjprice101** [comment]
@JEThompson97 It appears you did this during another PR as the duplicate fields are removed and the file doesnt exist anymore

**Comment by JEThompson97** [comment]
I'm just the gift that keeps on giving 😎
