### ISSUE TITLE
Improve logging in End of Run Monitor

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#59]
Currently the logging in end of run monitor is sparse, and also contains lots of STOMP queue logging. 
Adding better logging will allow us to see how the End Of Run Monitor is performing.
For example:
- Log which instruments we're watching on startup
- Add some debugging to log

**Comment by ElliotAOram** [comment]
Ensure logging path is not relative to avoid logging file being created in site-packages (due to windows service)
