### ISSUE TITLE
Create Mapping for Autoreduction Instruments and ISISICAT Instrument Prefixes

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#602]
Issue raised by: developer

### What?
Inability to find Instruments and associated runs when manually submitting run numbers if the prefix chosen by ICAT for the instrument doesn't match the full name.

As a temporarily, but potentially long lasting fix, we should create an explicit, hard coded mapping to map all ICAT instrument prefixes to their full instrument name. 

In the future, it would be nice to simply be able to query ISISICAT to get an explicit mapping of full instrument name and associated prefix. 

### Where?
* scripts/manual_operations/manual_submission.py
* utils/clients/tools/isisicat_prefix_mapping.py
* utils/clients/tools/tests/test_isisicat_prefix_mapping.py

### How?
When running manual submission for a given run or range of runs for an instrument, the database is first checked to see if the runs already exist inside Autoreduction. 
If they do not, they are then searched for in ICAT using the instrument name and run number. ICAT doesn't consistently use the full instrument name. 

ICAT picks a prefix (currently unsure is there is any consistency to this picking process). 
This means that when we are searching for an instrument using the full name, the instrument and associated runs may not be found if the prefix differs from the full instrument name. 

For example, the instrument MARI is called MAR in ICAT, but ENGINX is still ENGINX. 

### How to test the issue is resolved
* Ensure there is no drop in coverage
* Ensure all unit tests pass
* Ensure that manual submission works for instruments that use a shortened prefix in ISISICAT such as MARI.
* Code review

**Comment by ElliotAOram** [comment]
@JackEAllen do you think this would be a good new starter issue? Atleast if we are going down the route of hard coding the mapping table?

**Comment by ElliotAOram** [comment]
This can ("SHOULD") also be used in the webapp when assigning Regex to look for images.
