### ISSUE TITLE
Queue Processor Refactor/Rewrite

### ISSUE THREAD

**Issue by DavidFair** [ISISScientificComputing/autoreduce#604]
Following discussion with @ElliotAOram the rough outline is:

**Document existing implementation**
- UML Activity Diagram
- Acceptance tests based on existing behaviour 

**Potential Approaches**

~~*Python Daemon which spins up new processes:*~~
Cannot use directly, see below comment:

Pros:
- Fails once if something goes wrong
- Simple logging
- Easy start / stop point
- Can avoid race between GID updating and up polling message

Cons:
- Getting new process to pick up group ID
- Process pool handling
- Stateful

*Cron Job*
Pros:
- Stateless
- Guaranteed to pick up new GID
- Simple poll, act, exit mechanism

Cons:
- Will keep restarting even in failure state
- Ensuring logs with relevant failures don't get overwritten
- More difficult (in comparison) to simply start or stop

Requirements:
- Same output from given inputs as we currently have
- Must pick up new groups on start from the Kernel, so cannot use any forking approaches
- (Identify any more)

**Comment by DavidFair** [comment]
Note: For prototyping:

The current groups can be seen in `/proc/<pid>/status` under the `Groups` section
A nice demo to check we can spawn threads (and how easy it will be) is to spin up Daemon A, add the user to group foo, then check that the child process has the new GID (by printing or comparing outputs?)

**Comment by keiranjprice101** [comment]
see #967
