### ISSUE TITLE
Manual Operations Utility Centralisation

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#607]
Issue raised by: developer

### What?
Centralise methods performing the same or similar processes in `manual_remove.py` and `manual_submission.py` in a `utils.py` script to reduce redundancy/duplication.

Move methods listed below into separate script `utils.py`:
* `handle_input()`
*` user_input_check()`

### Where?
Scripts to remove redundancy from:
* `scripts/manual_operations/manual_remove.py`
* `scripts/manual_operations/manual_submission.py`

Create utils script here:
* `scripts/manual_operations/utils.py`
* `scripts/manual_operations/tests/test_utils.py`

### How?
A need to develop constantly DRY (don't repeat yourself) code to follow project standards

### How to test the issue is resolved
* Ensure all unit tests for `manual_remove`, `manual_submission` and `utils.py` pass
* No drop in coverage
* Code review
* Manually test `manual_submission.py` and `manual_remove.py`

**Comment by ElliotAOram** [comment]
@JackEAllen maybe we don't have to reinvent the wheel here? for once setting things on fire might be a good option 🔥 
 https://github.com/google/python-fire
