### ISSUE TITLE
Discuss: Rename master->stable-x and develop->master

### ISSUE THREAD

**Issue by DavidFair** [ISISScientificComputing/autoreduce#611]
Currently we use `master` as our stable release branch, whilst `develop` is effectively our master. This means developers need to remember to:

- Change their base branch when opening PRs
- Set any CI tasks to work from develop instead of master
- Never push to master (if they can)
- It may be more subtle just after they release causing accidental commits to master where someone forgets to change their base branch.

Proposal: 
- Use `stable_xx_xx` naming for each release, where `xx_xx` is the release or cycle name
- Migrate our current master to use the current name
- Continue using `develop` until our next release. Create a new `stable_xx_xx` branch and merge into master (as per what we do already)
- Then drop `develop` and continue on master

Pros:
- Any future tools and devs expect master by default rather that develop
- An accidental push or merge to master does not cause headaches for deploying releases from git
- We can revert a full release if something dire happens. This is very difficult with our current master

Cons:
- CI tools need to be pointed back to master
- Multiple stable branches will need pruning after a period of time (how many do we keep?)
- (Something else someone else can see?)

**Comment by ElliotAOram** [comment]
@DavidFair thanks for writing this up. This is actually on the cards for the next time we do a release but not documentated anywhere so really useful to have this written down here.

We have yet to pick a release date but I'm hoping to do one in the next couple of months (before september when the short remote cycle is scheduled) once that happens, I'll be looking to also make this workflow change 👍
