### ISSUE TITLE
Manual submission will fail on first run from a new IP

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#661]
Issue raised by: [developer]

### What?
The first manual submission from a new IP will fail. An `IncompleteRead` will be raised. The second attempt will run fine.

### Where?
Where is the issue likely to be (be as specific as possible)
See `manual_submission.py`

### Reproducible?
Yes

### How to test the issue is resolved
To reproduce run a manual submission from a new IP. e.g `python manual_submission.py <Instrument> <Run Number>`

**Comment by Anders-Markvardsen** [comment]
@keiranjprice101 can you specify what IP stands for please, thanks

**Comment by dtasev** [comment]
That's a hard one to test.. We'll probably never look at it but I'll leave it open
