### ISSUE TITLE
Missing mocking in test_get_status_valid

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#668]
Issue raised by: [developer]

### What?
The test `test_get_status_valid` is not mocking the data access logic and is querying the database / creating a row in `reduction_viewer_status` with value "valid"

### Where?
Where is the issue likely to be (be as specific as possible)
`test_status_utils.py` line 54

![image](https://user-images.githubusercontent.com/44777678/87529886-899eed00-c687-11ea-9334-fee7e950891a.png)

### Reproducible?
[Yes]

### How to test the issue is resolved
A set of instructions / A script / Include test files if required
Remove the valid row / test on a different value and check that the row is not inserted.

**Comment by dtasev** [comment]
Ah well it's looking for "c" now so it just gets or makes a Complete status
