### ISSUE TITLE
A number of CSS rules are overridden

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#687]
Issue raised by: [developer]

### What?
Some of the custom CSS rules are overridden by bootstrap:
An example:
In `base.css` we define:
```css
.navbar-brand {
    padding:10px;
}
```
This style is is overridden as shown:
![image](https://user-images.githubusercontent.com/44777678/88913806-8eec6200-d259-11ea-915e-2cf810dfcb17.png)

## Where?
`WebApp/autoreduce_webapp/templates/base.html` and possibly more of the templates
`WebApp/autoreduce_webapp/static/css/base.css`

### How?
This is probably caused by bootstrap being added after `base.css`. This is odd as in `base.html` bootstrap is included before our custom css, but when the page loads it is included twice. Once before and once after. This seems to only effect local deployment and production, the issue doesnt appear to happen on dev (Only checked dev briefly).
![image](https://user-images.githubusercontent.com/44777678/88914090-00c4ab80-d25a-11ea-9ec2-73e03a4f9e2e.png)

### Reproducible?
[Yes]

### How to test the issue is resolved
Simply check that the CSS rules in `base.css` are not overridden by bootstrap. Will need to try and determine which custom styles are effected.

**Comment by rickybassom** [comment]
#720 fixes this
