### ISSUE TITLE
Improve Webapp help page search

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#699]
Issue raised by: [developer]

### What?
The webapp help page search bar doesn't work very well. It states that it is found by key word search but some obvious keywords that are even  in the text do not discover content some examples of this are: `ISIS`, `Accessing`, `Compute`, `vars`

We should investigate how this is normally done - I would imagine there are very common framework/libraries for this - and implement one.

### Where?
Webapp help pages

### How?
Manual testing

### Reproducible?
Yes

### How to test the issue is resolved
* Use more generic keyword to search and ensure sane results
* Search for words that exist in the text and ensure they are found

**Comment by rickybassom** [comment]
As mentioned [here](https://github.com/ISISScientificComputing/autoreduce/issues/788) topic modelling could be used to generate keywords for topics to improve search.
