### ISSUE TITLE
STFC branding is out of date

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#731]
Issue raised by: [developer]

### What?
The STFC branding is out of date. We should update the logo to the new branding

### Where?
`WebApp/autoreduce_webapp/static/images/logo.png`

**Comment by JackEAllen** [comment]
Closing as Duplicate #429 This issue currently being worked on by myself https://github.com/ISISScientificComputing/autoreduce/issues/429
