### ISSUE TITLE
Unit Test Loading of Reduction Script as Module & Checking For Skipped Runs

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#732]
Issue raised by: developer

### What?
Currently the methods which load a reduction script as a module and check for skipped runs within post-process admin are unitestested due to the complexity of testing them and my own time constraints. 

We should create unit tests for both methods. 

This will be a complex task, however, once accomplished, these tests will arguably be the most useful tests within Autoreduction. 

### Where?
* queue_processors.autoreduction_processor.post_process_admin
    * PostProcessAdmin.reduction_as_module
    * PostProcessAdmin.check_for_skipped_runs
* queue_processors.autoreduction_processor.tests.test_post_process_admin
    * TestPostProcessAdmin.test_reduction_as_module
    * TestPostProcessAdmin.test_check_for_skipped_runs

### How?
* A need to unit test the loading of reduction scripts as a module
* A need to unit test checks for skipped runs
* To increase coverage 
* Improve debugging

### How to test the issue is resolved
* Code review
* Unit tests are valid (For added reassurance given the complexity of testing them)
* Unit tests pass
* No drop in coveralls

**Comment by keiranjprice101** [comment]
Code has been updated heavily since issue
