### ISSUE TITLE
Containerise Autoreduction Databases

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#734]
Issue raised by: developer

### What?
Please note that due to the size of this task, it may be worth creating a project and breaking this task down into smaller, more manageable tasks. 

This GitHub Wiki should aid in giving you a headstart with containerising databases: [AutoreductionMonitor Wiki](https://github.com/ISISSoftwareServices/AutoreductionMonitor/wiki/Containerisation_overview)

Create a containerised version of Autoreductions Production and Development Databases.
Containerising Autoreductions databases will bring many benefits (just a few of which have been listed below):
* Compartmentalise's Database
* Allows for the easy upgrading of MySQL
* Allows for creating and testing of new schemas with ease
* Allows for many individuals to test on the Autoreduction database without clashing/affecting each others work.

Please follow this link to edit the ERD diagram using [diagrams.net](https://app.diagrams.ne) : [AR_Containerised_DB_Architecture_Draft]( https://drive.google.com/file/d/1NMjl5VXrwixRV5Ny6a3-uE33XvxU9Pj7/view?usp=sharing)

![AR_Containerised_DB_Architecture_Draft](https://user-images.githubusercontent.com/32413847/91288240-ac451b00-e788-11ea-9160-0c8ca390be95.png)

### Where?
A new directory - docker_db/
Database containers should be placed in corresponding locations to current architecture after first testing both locally and on a dev node.

### How?
* Create a schema file for the autoreduction database (you can do this pretty easily in MySQL Workbench)
* Create two data volume containers (one for production and one for develop) mounting to two seperate storage locations containing data for the Autoreduction database. The develop data volume should only contain the last cycles worth of data.
* The dev data volume should only contain one cycles worth of data. 
    * The dev container should be overwritten automatically at the end of each cycle with the last cycles worth of data from the production datavolume.
    * We should also be able to manually populate the development data volume with a custom amount of data from production (run a script which will allow for the entering of a cycle/range of cycles or a date/range of dates.)
* Create a means of periodically backing up the production data volume externally to the container to be used should the production data volume have a critical failure of some sort I.E. the container shuts down.  - This link will be useful: [Docker Data Volume Backup](https://docs.docker.com/storage/volumes/#backup-a-container)
* Using the schema file, create 2 conterised instances of the Autoreduction database (one for development and one for production pointing to the corresponding data volumes)
* Finally, document your work in a README.md in the same directory - See [Autoreduction best practices - documentation](https://github.com/ISISScientificComputing/autoreduce/wiki/Best-Practices#documentation). Documentation should include the following points:
    * Overview of directory 
    * Directory contents (including container architecture)
    * Usage with examples
        * How to create the containerised databases (dev and production)
        * How to make many instances of the develop database container pointing to the same data volume.
        * How to test everything is working as expected

### How to test the issue is resolved
A set of instructions / A script / Include test files if required
As this is quite a significant task, i recommend that this is tested by the whole team.
* I recommend running both the containerised database in parallel to the existing architecture for one cycle to monitor (we want to be very cautious in switching over.
* Documentation has been reviewed by whole team.
* Databases are accessible outside of containers. 
* Containers are correctly built and behave as expected
* The develop data volume is periodically overwritten with the last cycles worth of data at the end of a cycle
* A script can be ran to manually overwrite the develop data volume with a custom selection of data (specific cycle/range of cycles or a date/range of dates)
* The production data volume backs up data automatically
* We can easily retrieve data from the backup datastore if a critical error occurs in the production data volume (container is shut down)

**Comment by dtasev** [comment]
I think I can close this for now, probably not going to be looking at it soon and with SQLite3 as development backend local deployment is a lot easier as no MySQL drivers/installation is needed.
