### ISSUE TITLE
Convert all CSS Within Webapp to Sass (SCSS)

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#735]
Issue raised by: developer

### What?
Convert all existing css in the webapp to be scss. 
scss is a a css precompiler which allows for easier and DRY styling of webpages. 
scss is a much more modern approach to web design, chosen to be used even by [Bootstrap 4](https://getbootstrap.com/docs/4.0/getting-started/theming/#sass)  who now offer .scss equivalents for all .css files.

There are many arguments why we should use sass for development over regular css which can be read about [here](https://www.mugo.ca/Blog/7-benefits-of-using-SASS-over-conventional-CSS).
Alternatively, you can simply navigate to [Sass's website](https://sass-lang.com/). 

### Where?
* WebApp/autoreduce_webapp/static/*.css

### How?
To make stylistic changes easier to manage and to follow existing trends in web development. 
To be able to use variables, maps, mixins etc.

### How to test the issue is resolved
* All existing .css has been converted to .scss
* Webapp is identically styled to regular css version of webapp.

**Comment by dtasev** [comment]
Some day, not a priority and probably won't need it until we start rewriting huge chunks of the web app, at which point it'll probably come naturally
