### ISSUE TITLE
Update Logging Usage Throughout Autoreduction

### ISSUE THREAD

**Issue by JackEAllen** [ISISScientificComputing/autoreduce#742]
Issue raised by: developer

### What?
Now we have a [new logging utility package](https://github.com/ISISScientificComputing/autoreduce/pull/741), we should remove all logging setup scripts and usage of other custom loggers and/or direct use of built in logging import to use the new utility to centralise where logging is configured and called from. 

###Where?
New logger location: `utils/logger`

### How?
A need to centralise logging and enforce a uniform logging format throughout codebase

### How to test the issue is resolved
* Code review
* All Unit tests pass for scripts updated to use new logger
* all previous log setup scripts have been removed
* All logs output to the correct/appropriate locations

**Comment by keiranjprice101** [comment]
Logging utility package not added.
