### ISSUE TITLE
Manual submission failures

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#749]
Issue raised by: [developer]
### What?
Manual submission will sometimes fail with EOF

### Where?
`manual_submission.py`

### How?
Potentially related to fire, as this is not recorded prior to its inclusion

### Reproducible?
[Yes]
Intermittently but no exact cause identified as of yet.

### How to test the issue is resolved
Once the cause has been identified we would hope to be able to reproduce this and test it is resolved.

**Comment by dtasev** [comment]
Can't tell what could be causing this form the description and haven't seen this, so closing this for now
