### ISSUE TITLE
Identify and document what is happening with VariableUtil

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#757]
Issue raised by: [developer]

refs #739 

### What?
There are 2 classes `VariableUtils` in `queue_processors/queue_processor/queueproc_utils/variable_utils.py` and `VaribleUtils` in `WebApp/autoreduce_webapp/reduction_variables/utils.py` 
We need to identify why these 2 classes are almost identical and if they can be combined.

### Where?
 `queue_processors/queue_processor/queueproc_utils/variable_utils.py`
`WebApp/autoreduce_webapp/reduction_variables/utils.py` 

### How?
How did the issue come about

### Reproducible?
[Yes]

### How to test the issue is resolved
Merge these 2 classes, or document why both are needed

**Comment by dtasev** [comment]
Painfully done by #1022
