### ISSUE TITLE
Investigate why no advanced variables are available for WISH

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#761]
Issue raised by: [developer]

### What?
When rerunning a WISH run, no advanced variables are available. Found in #750 We will need to work out why, and fix or document this.

### Where?
This will need to be identified

### Reproducible?
[Yes]

### How to test the issue is resolved
Advanced variables will be available or we will document why they are not for WISH

**Comment by Anders-Markvardsen** [comment]
WISH has no variables set and thanks for checking
