### ISSUE TITLE
Update wiki for easier Linux queue processor setup

### ISSUE THREAD

**Issue by rickybassom** [ISISScientificComputing/autoreduce#772]
Issue raised by: developer

### What?
The wiki could be improved to make it easier for new developers to setup the project as mentioned here #708 .

### Where?
autoreduce > Wiki > Setup

### How?
Reviewing the wiki pages for this PR #708

### Reproducible?
Yes

### How to test the issue is resolved
I have outlined 3 things that should be changed:
- When doing a fresh clone and going through the setup tutorial on Fedora 31 I discovered that the Install external programs section only works on Debain/Ubuntu based Linux distributions since apt is not available on Fedora/Centos etc... It should be mentioned in the wiki that the python setup.py externals command can only be executed on Debain/Ubuntu based Linux distributions. As a work around I installed activemq manually.

- I don't think there's anywhere in the wiki that mentions adding your mysql credentials to credentials.ini for development.

- A small section that tells the developer how to run the queue processor and WebApp straight after the Setup section could be added.

**Comment by dtasev** [comment]
I think this can be done as part of a larger wiki-overhaul to get everything up to speed https://github.com/ISISScientificComputing/autoreduce/issues/1249
