### ISSUE TITLE
Investigate reset values option in reruns

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#774]
Issue raised by: [developer]

### What?
The additional action shown below is unclear for users. It is a hyperlink that appears to go nowhere, and is unclear if it does anything. There is help text that is in the page but is not displayed.
It might be worth changing this to be a tickbox like the option below it.
![image](https://user-images.githubusercontent.com/44777678/93331276-e77ebb00-f817-11ea-94de-5e48ae4b2907.png)

### Where?
`WebApp/autoreduce_webapp/templates/submit_runs.html`

### Reproducible?
[Yes]

### How to test the issue is resolved
Help text should be visible/ be able to be triggered.
It should be clear what has happened when this is selected/clicked.

**Comment by Anders-Markvardsen** [comment]
Find this work during smoke testing. Hyperlink now works and reset back to values in script and help text is displayed

![Capture](https://user-images.githubusercontent.com/1135476/113743479-a1c60900-96fb-11eb-843a-63fe277fe8d8.PNG)
