### ISSUE TITLE
Display reduction variables in the rerun page

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#778]
Issue raised by: [developer]

### What?
It should be possible to see the current reduction variables in the rerun page. It would also be a good idea to veirfy  whether the "reset variables" "additional action" is working, and reformat it so the help is displayed. (similar to #775)
### Where?
`WebApp/autoreduce_webapp/templates/submit_runs.html`

### Reproducible?
[Yes]

### How to test the issue is resolved
The reduction variables should be visible and the reset variable action should be reformatted.

**Comment by dtasev** [comment]
Isn't this the default behaviour - the latest reduction variables' values is shown? Whether reset variables works is a good question though

**Comment by dtasev** [comment]
I'll close this until requested by users
