### ISSUE TITLE
Plot finding seems limited to be only for MARI and WISH

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#794]
Issue raised by: [developer/user/project requirement]

### What?
The code that generates the regex for the filename of the saved plot image seems to expect only MARI and WISH.
This [dictionary](https://github.com/ISISScientificComputing/autoreduce/blob/master/plotting/plot_handler.py#L23) provides the patterns used to find the plot files. It only contains MARI and WISH, so any other instrument with a plot will immediately `return None` for the filenames [here](https://github.com/ISISScientificComputing/autoreduce/blob/e68548a915716354f308dcf8f44add32e7aae95e/plotting/plot_handler.py#L53-L57)

### How?
Trying to retrieve plots for instruments was causing #760 

### Reproducible?
Yes, go to `/runs/HRPD/78938/30/` - no plot will be shown, although one is available due to testing for #793 

### How to test the issue is resolved
Plots should show for `/runs/HRPD/78938/30/` (it's just a simple sine wave plot, not anything from the data itself)

### To fix
Either:
- add a key for every supported instrument in autoreduction
- or add a wildcard using the instrument name assuming the pattern `<INSTRUMENT_NAME><RUN_NUMBER>.png` to look for filenames

### Thoughts
The 2nd option shouldn't be an issue anymore, as after #793 the page will be rendered even if plot files are missing or encounter an error during retrieving.

We likely want to handle the case where plot files are expected BUT missing, which could be made harder with a wildcard

**Comment by Anders-Markvardsen** [comment]
Just to note, observe this bug just now also for OSIRIS. I.e. changed reduce.py to output plot. This create the following output on CEPH

```
[isisautoreduce@autoreduce autoreduction]$ ls /instrument/OSIRIS/RBNumber/RB1920701/autoreduced/144370/run-version-0/
OSIRIS00144370.nxs  reduction_log  TEST_PLOT.png
```

However no plot in the webapp

![image](https://user-images.githubusercontent.com/1135476/98569180-df884800-22a9-11eb-859b-4b10b8eed7cf.png)

**Comment by Anders-Markvardsen** [comment]
Concerning the suggestions for fixes and as discussed yesterday. I favour making plotting entirely instrument agnostic, i.e. with no instrument check. If we for some reason in the future we have user wanting this to be restricted somehow then we can implement at that point. Also, I currently can't see a non-functional requirement for implementing restriction in code for plotting.
