### ISSUE TITLE
scripts and calibration files from same access mechanism

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#8]
Issue raised by: [developer]

### What?
Move where the instrument scientists scripts are stored to be on the samba share along with the calibration files. This will remove the dependency on the isis data archive further (improving ease cross facility collaboration potential)

### Where?
External - however some changes to the `QueueProcessors` and `webapp` settings will be required. 

### How to test the issue is resolved
Ensure that autoreduction functions correctly end to end 
* `python scripts\manual_submission\manual_submission <INST> <RUN-NUMBER>`

**Comment by ElliotAOram** [comment]
Not required. We should be moving away from the Samba share approach and other methods
