### ISSUE TITLE
Disable overwrite option for flat output instruments

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#801]
Issue raised by: [developer]

### What?
Because a flat output instrument will not have subfolders, preventing overwrite is not possible. We need to disable this checkbox and communicate that the data will always be overwritten for these instruments. However, as the web app is run from within the web app directory. It *may* not be easy to access the `flat_output_instruments` setting in `queue_processors/autoreduction_processor/settings.py`

### Where?
`queue_processors/autoreduction_processor/settings.py`
`WebApp/autoreduce_webapp/templates/submit_runs.html`

### Reproducible?
[Yes]

### How to test the issue is resolved
The option to not overwrite a run should not be given to flatoutput instruments.

**Comment by dtasev** [comment]
Related to #957
