### ISSUE TITLE
Graceful shutdown of queue processors

### ISSUE THREAD

**Issue by jsws** [ISISScientificComputing/autoreduce#81]
It would be nice to have a way to gracefully shutdown both the queue processor and autoreduction processor so that reduction runs don't get stuck in a bad states.

When the graceful shutdown is initiated the queue processors will finish with the reduction runs they're currently processing before exiting.

**Comment by ElliotAOram** [comment]
Not feasible with python and activemq due to the way the queues have to been looked at. Agreed that this would be nice but not worth the overhead now we have the ability to remove these by hand
