### ISSUE TITLE
Make manual submission create instruments

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#840]
Issue raised by: [developert]

### What?
If an instrument does not already exist within the database, the manual_submission script should create it.

Be careful to take in to account possible typos.
Check `access.py` for create flag

### Where?
`scripts/manual_operations/manual_submission.py`

### How?
How did the issue come about

### Reproducible?
[Yes]

### How to test the issue is resolved
The manual submission should be able to create an instrument that doesn't exist before submitting the run.

**Comment by dtasev** [comment]
This should be fixed now, but only because the queue_processor now does a `Instrument.get_or_create(name=...)`, rather than in `manual_submission `
