### ISSUE TITLE
Make run_detection use VALID_INSTRUMENTS

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#841]
Issue raised by: [developer]

### What?
Make `run_detection.py` use VALID_INSTRUMENTS.
As currently `use_nexus` is always true, we can use `VALID_INSTRUMENTS` from `utils.settings`

### Where?
`monitors.run_detection`
`utils.settings`

### How?
Working towards having a single place to add instruments.

### How to test the issue is resolved
Runs can still be picked up when using the instrument list from `utils.settings.VALID_INSTRUMENTS`

**Comment by dtasev** [comment]
I think this is referring to https://github.com/ISISScientificComputing/autoreduce/blob/master/monitors/test_settings.py#L25-L30? In which case I cannot find any usages of that variable so I think it can just be deleted!

**Comment by dtasev** [comment]
We removed all of these unused variables so this issue can be closed
