### ISSUE TITLE
Investigate why the RB number in the message and the view differ

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#855]
Issue raised by: [developer/user/project requirement]

### What?
![image](https://user-images.githubusercontent.com/1135476/96588120-243c4700-12db-11eb-85b7-2f107fd10545.png)
The message shows RB: CAL_GEM_.... and the run summary shows RB 0. We need to identify this discrepancy and amend it.

### Where?
`WebApp/autoreduce_webapp/templates/run_summary.html`

### How?
Smoke testing

### Reproducible?
[Yes]

### How to test the issue is resolved
The correct RB should be shown in both instances

**Comment by dtasev** [comment]
I think we found the reason with #1118 - it's because invalid RB numbers are set to 0
