### ISSUE TITLE
Every Larmor run is being skipped

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#856]
Issue raised by: [developer]

### What?
Every LARMOR run is being skipped. We need to identify why. It is possibly related to #855 
Where is the issue likely to be (be as specific as possible)

### How?
Smoke testing

### How to test the issue is resolved
It should be possible to run LARMOR jobs

**Comment by Anders-Markvardsen** [comment]
Fixed in PR. Larmor instrument scientist Rob report that his Larmor reduce.py script works
