### ISSUE TITLE
DataArchiveCreator prevents changes to settings.py

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#875]
Issue raised by: [developer]

### What?
This is pretty convoluted to explain so I will try to bullet point it
- `queue_processors/autoreduction_processor/test_settings.py` has 2 settings `ceph_directory` and `scripts_directory`. (As of right now there is also a comment above them that shows the settings used for the dev node and probably prod)
- In `test_end_to_end.py` the class `DataArchiveCreator` is used to setup a fake data archive for storing datafiles/scripts/etc. 
- The `DataArchiveCreator` will only set up a directory that matches the current value in `test_settings.py` This means 2 different things: 
  * If those settings are ever changed `test_end_to_end.py` will break, as the `DataArchiveCreator` is not using the setting but is hardcoded to create a directory matching the setting as it exists right now.
  * The production and development builds would technically fail these 2 end to end test cases, more generally, the end to end test only tests the software in one specific configuration, that is only used in travis and not anywhere else
 - The docstring for `DataArchiveCreator` also claims to produce an archive identical to isis data archive. It doesn't

### Where?
Settings at  `queue_processors/autoreduction_processor/test_settings.py` 
Archive creator at `utils/data_archive/data_archive_creator.py`
tests at `systemtests/test_end_to_end.py`

### How?
A need to change the settings revealed this.

### Reproducible?
[Yes]
Change the setting and these 2 tests will fail.

### How to test the issue is resolved
The DataArchiveCreator should create a data archive based on the 2 settings from the settings file, not hard coded location. The end to end tests should then be able to pass on any environment (including dev and prod in theory)

**Comment by dtasev** [comment]
Might be fixed via changes in https://github.com/ISISScientificComputing/autoreduce/tree/queue_processor_refactor

**Comment by dtasev** [comment]
I touched this in #1022 but I'm not sure how far this has been fixed.

The DataArchiveCreator doesn't use any of the settings.py so the `test_end_to_end` will still fail (even with the rewrite) if the script_directory is changed.

Maybe making a new variable that holds the `ARCHIVE_ROOT={PROJECT_ROOT}/data-archive` path and builds `SCRIPTS_DIRECTORY = f"{ARCHIVE_ROOT}/NDX%s/user/scripts/autoreduction/"`. Then on dev/prod we just make `ARCHIVE_ROOT=/isis` and all should work.
