### ISSUE TITLE
upload scripts to github repository

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#9]
Issue raised by: [developer]

### What?
Create cron job for uploading script to github repository for users and us to see global history. Create seperate github user, which could be isisautoreduce, and seperate repository, which could be autoreduce-cron

### How to test the issue is resolved
* Ensure that scripts - with changes are getting uploaded periodically to the new github repository by the new github user

**Comment by ElliotAOram** [comment]
superseded by #379
