### ISSUE TITLE
Make RB validation more specific

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#901]
Issue raised by: developer

### What?
In:

```
def validate_rb_number(rb_number):
    """
    Detects if the RB number is valid e.g. (above 0 and not a string)
    :param rb_number:
    :return: False If the RB is not valid, otherwise true
    """
    try:
        rb_number = int(rb_number)
    except (ValueError, TypeError):
        return False

    return rb_number > 0
```

This does not catch all invalid RB numbers. On https://www.isis.stfc.ac.uk/Pages/Digital-Object-Identifiers-(DOIs)-for-ISIS-Data.aspx it reads "RBxxxxxxx where xxxxxxx is the 7-digit RB number"

Modify validate_rb_number to match this.

### How to test the issue is resolved
Add unit tests as appropriate.

**Comment by keiranjprice101** [comment]
closed in #977
