### ISSUE TITLE
Enable additional location(s) where reduced data could also be stored to

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#907]
Issue raised by: Rob Dalgliesh

### What?
Allow additional location(s) where reduced files can be optionally stored to. That is optionally additional storage location to current CEPH.

Such specific other areas of course needs to be mountable from compute nodes. Rob is asking in this case for storing within `\\isis\inst$\NDX###\User\script\autoreduction` (which we currently already have read/write access to). 

We can make this feature available in multiple ways.

Rob prefers this to be made available via the reduce.py/reduce_vars.py scripts. As such it is a feature made available with the understanding that the author of reduce.py knows additional storage areas have the necessary available disk space (in Rob case this is not an issue with small reduced file sizes).

This could be implementation and exposed to reduce.py in a number of ways, and with how such additional locations are displayed on run pages on the webapp.

Before implementing solution please first discuss ideas with other team members and then get Rob's feedback.

**Comment by dtasev** [comment]
Closing as it's not a current requirement, but parts of the DB still refer to this design (e.g. the ReductionRun 1->* DataLocation #1050)
