### ISSUE TITLE
Coveralls is broken

### ISSUE THREAD

**Issue by rickybassom** [ISISScientificComputing/autoreduce#911]
Issue raised by: [developer]

### What?
Coveralls is broken

![image](https://user-images.githubusercontent.com/5902731/98825591-93194580-242c-11eb-8d63-135fe81dc2aa.png)

### Where?
https://coveralls.io/github/ISISScientificComputing/autoreduce?branch=master

No errors are logged on Travis for PRs.

### Reproducible?
[Yes]

### How to test the issue is resolved
* Can view code coverage again

**Comment by dtasev** [comment]
Yep, it's been broken for a bit. I tried re-adding it but it doesn't seem to pick up any of the builds and I'm not sure why (https://coveralls.io/github/ISISScientificComputing/autoreduce)
