### ISSUE TITLE
Mark which parts of the projects use which depenency

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#926]
Issue raised by: [developer]
### What?
To make testing dependabot PRs easier, it would be good if we commented which part of the system uses which dependency in requirements.txt and setup.py e.g. `#WebApp` or `#queue_processors`

### Where?
`requirements.txt`
`setup.py`

**Comment by dtasev** [comment]
I don't think we'll do this and it'll be a bit of a nightmare to keep it up to date
