### ISSUE TITLE
test_filter_files_by_time_add_multi

### ISSUE THREAD

**Issue by keiranjprice101** [ISISScientificComputing/autoreduce#931]
Issue raised by: [developer]

### What?
`test_filter_files_by_time_add_multi` This test is failing on the github test job on the master branch.

It is not failing locally for me

### Where?
`utils/data_archive/tests/test_file_filter.py`

### How?
See https://github.com/ISISScientificComputing/autoreduce/actions/runs/372579810
### Reproducible?
[Yes]

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by rickybassom** [comment]
I was literally just writing this up too :smile: 

It would be interesting if we could test this on Travis too.

**Comment by keiranjprice101** [comment]
Interestingly this test passed in #933 while it was in PR. Then this test failed once the action ran again on the merge commit 35a39be

**Comment by rickybassom** [comment]
We could try logging `ll /tmp/...` to look at the mod times of the files created [here](https://github.com/ISISScientificComputing/autoreduce/blob/35a39becc612a518d9189838a73d522fe89118ac/utils/data_archive/tests/test_file_filter.py#L118) to see if `filter_files_by_time` is broken. But we need to find a way of testing this without merging it first.

**Comment by rickybassom** [comment]
Just reran it on master and it passed

**Comment by keiranjprice101** [comment]
The consistency is scary 😨
