### ISSUE TITLE
HRPD run falsely reported as skipped

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#935]
Issue raised by: developer

### What?

Run HRPD 78271 appears to have run number 2035000 according to journal viewer

However just running now on webapp and see

![image](https://user-images.githubusercontent.com/1135476/99786755-c9368380-2b16-11eb-9b59-cbe7d0868738.png)

**Comment by keiranjprice101** [comment]
@Anders-Markvardsen We have checked the data catalog and this is appears as a calibration run with the same RB as the error gives. I am not familiar with the journal viewer to recheck there however. So there may be a discrepancy

**Comment by rickybassom** [comment]
Ingestion / ICAT also treats RBs of 0 as calibration runs. https://github.com/ral-facilities/isis-icat-ingestion/blob/master/ICATLiveIngest/ICAT4IngestLibrary/InvestigationTypeDeterminer.cs#L60

**Comment by Anders-Markvardsen** [comment]
Both of you thanks. In that case Autoreduction code is OK since it picks up this info in this manual submit from ICAT and hence I am therefore closing this issue. Instead either this is bug with JournalViewer or this run was ingested wrongly into ICAT. The JournalViewer view is

![image](https://user-images.githubusercontent.com/1135476/99911227-cee4c280-2cea-11eb-968e-13997246691c.png)

@rickybassom for sanity sanity could you check RB 2035000 in ICAT
