### ISSUE TITLE
New PostProcessAdmin pushes jobs into stale queued state at midnight

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#943]
Issue raised by: developer

As of now we have these queued jobs for cycle 20_3

![image](https://user-images.githubusercontent.com/1135476/100002435-73830500-2dbc-11eb-84a3-65f2cbe04925.png)

each of which where last updated respectively:

* Last Updated: 19 Nov 2020, 11:43 p.m
* Last Updated: 21 Nov 2020, 11:43 p.m
* Last Updated: 22 Nov 2020, 11:41 p.m

basically these jobs started before the queue processor turned off 23:45 (from memory) and restarted again at midnight. 

This is strong evidence to suggest that any runs that have started before 23:45 and not finished before than ends up stale.

Larmor perhaps more than any instruments appears to run jobs around this time. 

### Where?
queue processors.

Note this was not an observed problem in cycle 20_2 because ran with older queue processors that not restarted and that it appeared that the old issue with permissions on CEPH no longer relevant. Hence, options seem to be available

* don't restart the queue processors at midnight and at most on maintenance days (and consider removing the feature for automatically restarting)
* find a fix, which is needed regardless (and there is probably a ticket for this already) since regardless we want to be able to gracefully restart the queue processor

or a combination of above.

### How to test the issue is resolved
A test which starts a job of some length say expected to run 3 seconds, stop the queue processors after one second and before the job has finished, wait for a second, restart the queue processor and see if job finishes about 2 seconds after restart

**Comment by keiranjprice101** [comment]
Interestingly if you start a job, then restart the queue_processors in the processing state. The job will not be stuck.

**Comment by Anders-Markvardsen** [comment]
@keiranjprice101 interesting and perhaps the reason is that this job has passed the Reduction Pending queue - not sure

In theory, and concerning 23:45: what I think should happen is that the queue_processor is asked to stop listening to the activeMQ Data ready queue, but otherwise both queue_processor and autoreduction_processor continue to be subscribed to all the other queues, including queue_processor continue to be subscribed Reduction Pending

**Comment by keiranjprice101** [comment]
@Anders-Markvardsen  As far as I am aware, since stopping the daily restart, there have been no more stale runs with this as the reason? If so should we close this.
