### ISSUE TITLE
Utils database helper methods require an temporary instance to be created

### ISSUE THREAD

**Issue by DavidFair** [ISISScientificComputing/autoreduce#95]
The current database access methods are class based. Currently we instantiate the class, use a method on it, then dispose it.

Instead the database access methods should be turned into static methods on the classes, and all callers updated.

**Comment by ElliotAOram** [comment]
This may change depending on the chosen implementation of the database rewrite. But it is important to consider how the ORM mapping will be handled

**Comment by ElliotAOram** [comment]
blocked by database redesign

**Comment by ElliotAOram** [comment]
Being resolve by #548
