### ISSUE TITLE
"Re-run past jobs" broken in WebApp

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#954]
Issue raised by: developer with user Tatiana

### What?
See animation below

![rerun_past_bug](https://user-images.githubusercontent.com/1135476/100432944-35befe80-3092-11eb-87a3-c1f5af0b6afd.gif)

Please restore the functionality previously working.

### Where?
Hopefully just limited to functionality broken in the webapp code

### Reproducible?
Yes

### How to test the issue is resolved
Manual test that it is fixed. Adding regression test may have to wait for #14 

This is less critical than #953 and for this reason not adding the backport label, but needs to be fixed for 20_4 release

**Comment by rickybassom** [comment]
This is difficult to reproduce but I think I found the cause:

* `submit_runs/` displays "Instrument is not active - it has no runs" when `instrument.is_active` is false.
* Some instruments currently appear to be deactivated in the database on production
  ![image](https://user-images.githubusercontent.com/5902731/100487300-b9630480-30ff-11eb-87f6-17c3d77fa490.png)
* In the past when we had a bug to do with reduction scripts not being found which might have caused `instrument.is_active = false`. https://github.com/ISISScientificComputing/autoreduce/blob/d801e27b7a96a281e6378ad4cdede9e79dfb3e6b/WebApp/autoreduce_webapp/reduction_viewer/view_utils.py#L32-L37

**Comment by rickybassom** [comment]
This issue is no longer visible on the production web app and there's nothing in the logs to say what was causing this. The only cause I can think of is from the code above.
