### ISSUE TITLE
Logged out users are missing "All Jobs" button

### ISSUE THREAD

**Issue by DavidFair** [ISISScientificComputing/autoreduce#96]
Logged out users are missing the navigation bar at the top of the website, making it difficult to get around.

**Comment by jsws** [comment]
"All Jobs" is effectively the home button, takes you back to the page that displays the instruments and runs.

**Comment by DavidFair** [comment]
I've replicated the issue, this should be about users who are not logged in not seeing the "All Jobs". I initially thought there was no button.

See attached screenshot: ![missing home](https://user-images.githubusercontent.com/1817032/41296206-570f73a6-6e54-11e8-90a1-439d266f548d.PNG)

I'll rename the issue and drop the priority in that case

**Comment by jsws** [comment]
Ah okay, this should only be an issue for local development environments where the `DEVELOPMENT_MODE` flag is set to True. Otherwise you have to be authenticated to view those pages.

**Comment by ElliotAOram** [comment]
We infact don't want the home button as non-authenticated users should not be able to see any runs at all for privacy details.
The `DEVELOPMENT_MODE` flag is now set to true in the test settings to avoid this scenario so we cna close this issue
