### ISSUE TITLE
Queue Processor redesign

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#967]
Issue raised by: develper

### What?
Discuss whether all 5 AMQ stages are necessary in the Queue Processor

It seems that not all 5 are required and there seems to be some unnecessary complication of the code in the queue processor (QP).

Currently it keeps moving messages in different queues, all while updating the DB on: `/DataReady, /ReductionStarted, /ReductionSkipped, /ReductionError, /ReductionComplete`.

It seems one of those updates is unnecessary: either keep the state to queues or keep it to the DB. Currently our state is mostly processed from the Queues and we get stale messages often. This is expected from Queues so it's probably better to move towards keeping the state in the DB

If we change the QP to have a simpler approach of:
- Get message from `/DataReady`
- Check if suitable for reduction - if so start a sub-processes performing the reduction
	- The subprocess is responsible for updating its state in the DB
	- All but `/DataReady` queues won't be used and can be removed

This change seems to be contained to the QP and ActiveMQ, and we don't necessarily even need to change the 2nd, but it would be good to clean up.

Pros:
- Less chance for losing job state - unless the subprocess magically disappears we can ensure that we have a job outcome
	- This should prevent stale jobs
- Potentially less DB hits - if possible to keep the job record reference we can queue the DB ONCE at the start, then just update state and save multiple times as we go through. 
	- So far it seems that saving a record whose reference we have is much cheaper than queueing for it again, especially when the DB grows
- This should make it easier to scale - especially if less DB hits turns out to be true
	- All we need then is multiple `/DataReady` consumers on different machines. This is also the case now, but I am not confident it will work well with the current arrangement, as we might just end up losing more messages!
- Should significantly reduce the code complexity in the QP package while doing the same thing

Time estimates:
- This doesn't look like more than a 2 week task, based on:
	- The rewrite itself is probably a couple of days or so, as most of it is a refactor
	- The testing will take more time, and we want to ensure the performance is OK
		- If possible to also test scalability that would be excellent, but I'm not putting that in the 2 week estimate

**Comment by keiranjprice101** [comment]
> unless the subprocess magically disappears 
If we move to multiprocessing this shouldnt be possible. In theory

Based on this and what we discussed yesterday. This should be much cheaper. At most 3 DB hits per run. Create Row -> Update to processing -> Update to Skipped/Completed/Error.

Good time to finally rename `PostProcessAdmin` too
