### ISSUE TITLE
Hard-coded MySQL parameters

### ISSUE THREAD

**Issue by rickybassom** [ISISScientificComputing/autoreduce#992]
Issue raised by: developer

### What?
Values like the MySQL database hostname and username are in places hard-coded.

### Where?
`build/database/reset_autoreduction_db.sql`
`queue_processors/queue_processor/settings.py`

### How to test the issue is resolved
* In the files above import `utils.settings` and use the options from `MYSQL_SETTINGS`.
* Tests pass

**Comment by dtasev** [comment]
I think I removed all of those in #1070
